package com.example.sakilaapi.model;// default package
  


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * com.example.sakilaapi.model.SalesByFilmCategory generated by hbm2java
 */
@Entity
@Table(name="sales_by_film_category"
    ,catalog="sakila"
)
public class SalesByFilmCategory  implements java.io.Serializable {


     private SalesByFilmCategoryId id;

    public SalesByFilmCategory() {
    }

    public SalesByFilmCategory(SalesByFilmCategoryId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="category", column=@Column(name="category", nullable=false, length=25) ), 
        @AttributeOverride(name="totalSales", column=@Column(name="total_sales", precision=27, scale=2) ) } )
    public SalesByFilmCategoryId getId() {
        return this.id;
    }
    
    public void setId(SalesByFilmCategoryId id) {
        this.id = id;
    }




}


