package com.example.sakilaapi.model;// default package
  


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * com.example.sakilaapi.model.StaffList generated by hbm2java
 */
@Entity
@Table(name="staff_list"
    ,catalog="sakila"
)
public class StaffList  implements java.io.Serializable {


     private StaffListId id;

    public StaffList() {
    }

    public StaffList(StaffListId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="address", column=@Column(name="address", nullable=false, length=50) ), 
        @AttributeOverride(name="city", column=@Column(name="city", nullable=false, length=50) ), 
        @AttributeOverride(name="country", column=@Column(name="country", nullable=false, length=50) ), 
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="name", length=91) ), 
        @AttributeOverride(name="phone", column=@Column(name="phone", nullable=false, length=20) ), 
        @AttributeOverride(name="sid", column=@Column(name="SID", nullable=false) ), 
        @AttributeOverride(name="zipCode", column=@Column(name="zip code", length=10) ) } )
    public StaffListId getId() {
        return this.id;
    }
    
    public void setId(StaffListId id) {
        this.id = id;
    }




}


